### ISSUE TITLE
Wired client-side js error after build. 

### ISSUE THREAD

**Issue by X7md** [vmware-samples/webassembly-browser-apps#5]
I was playground a little with website code...
I remove all components, and just keep `index.mdx`...

reproduce:
https://github.com/X7md/wasm-ssr/commit/209dea876066ff1eca18090aeeb86b86691f0170

all works good in dev `npm run dev`, and build have no error, but after run I face this error:
```js
autofill.js:10733 Uncaught TypeError: Cannot read properties of undefined (reading 'encrypt')
    at 45 (autofill.js:10733:33)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at 44../captureDdgGlobals.js (autofill.js:10579:49)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at 54.../../../packages/device-api/index.js (autofill.js:11616:25)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at 56../android.transport.js (autofill.js:11714:23)
``` 
![image](https://user-images.githubusercontent.com/54203033/188271505-8531bb03-507c-48b3-b2df-a2ac4fa26a40.png)

no problem with server, I think client-side bundle code have an issue or something...

**Comment by X7md** [comment]
sorry my bad...

It's chrome extension error.
